table mapp_api_query_7241_02
	lineageTag: b3052067-4ca8-4142-b201-558e7f674359

	column session_id
		dataType: string
		lineageTag: f4a4783b-650a-4b1d-bddc-00fbe0fd97ee
		summarizeBy: none
		sourceColumn: session_id

		annotation SummarizationSetBy = Automatic

	column time_days
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 5b4f4b5e-e015-4b2e-ae15-38526f1a7338
		summarizeBy: none
		sourceColumn: time_days

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

		annotation UnderlyingDateTimeDataType = Date

	column visit_time
		dataType: string
		lineageTag: f7bee64a-54eb-43c4-ad48-4f42836d2d88
		summarizeBy: none
		sourceColumn: visit_time

		annotation SummarizationSetBy = Automatic

	column visitors_newVsReturning
		dataType: string
		lineageTag: 7342b437-549d-400b-86f3-b5125de32438
		summarizeBy: none
		sourceColumn: visitors_newVsReturning

		annotation SummarizationSetBy = Automatic

	column pages_pageImpressions
		dataType: int64
		formatString: 0
		lineageTag: 184385ca-135f-46a9-aad0-97ee8ab6b788
		summarizeBy: sum
		sourceColumn: pages_pageImpressions

		annotation SummarizationSetBy = Automatic

	partition mapp_api_query_7241_02 = m
		mode: import
		source =
				let
				    Quelle = Databricks.Catalogs("adb-4119964566130471.11.azuredatabricks.net", "/sql/1.0/warehouses/59a74cf19690258c", null),
				    swi_audience_prd_Database = Quelle{[Name="swi_audience_prd",Kind="Database"]}[Data],
				    swiplus_Schema = swi_audience_prd_Database{[Name="swiplus",Kind="Schema"]}[Data],
				    mapp_api_query_7241_08_Table = swiplus_Schema{[Name="mapp_api_query_7241_02",Kind="Table"]}[Data],
				    #"Tipo cambiado" = Table.TransformColumnTypes(mapp_api_query_7241_08_Table,{{"time_days", type date}},"de-CH")
				in
				    #"Tipo cambiado"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Exception

